# Generated by Django 2.1.7 on 2019-02-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('job_text', models.TextField()),
                ('company', models.CharField(max_length=250)),
                ('positions', models.IntegerField()),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('link_to_apply', models.URLField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('last_date_apply', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Country'),
        ),
    ]
